name: BUild + Sonarr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  sonar:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SonarScanner for .NET 7 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.1.3
        with:
          # The key of the SonarQube project
          sonarProjectKey: billboard-api
          # The name of the SonarQube project
          sonarProjectName:  billboard-api
          # The SonarQube server URL. For SonarCloud, skip this setting.
          sonarHostname:  ${{ secrets.SONAR_HOST_URL }}
          # Optional command arguments to dotnet test
          dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          # Optional extra command arguments the the SonarScanner 'begin' command
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
        
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
